[Backing]
Meter=IMAGE
SolidColor=0,0,0,2
X=0
Y=0
W=#SidebarWidth#
H=28

[StyleLabel]
X=1
Y=2
H=13
W=(#SidebarWidth#-1)
FontColor=#Color1#
StringStyle=NORMAL
FontSize=#Height1#
StringAlign=LEFT
FontFace=#Font1#
AntiAlias=1
Text="#Label#"
ClipString=1

[StyleBar]
X=0
Y=14
H=2
W=#SidebarWidth#
BarColor=#Color1#
BarOrientation=HORIZONTAL

[BarBackground]
Meter=IMAGE
X=0
Y=14
H=2
W=#SidebarWidth#
SolidColor=160, 160, 160, 120

[StyleText]
X=1
Y=16
H=13
W=(#SidebarWidth#-1)
FontColor=#Color1#
StringStyle=BOLD
FontSize=#Height1#
StringAlign=LEFT
FontFace=#Font1#
AntiAlias=1
ClipString=1